services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CLOUDSQL_INSTANCE=${CLOUDSQL_INSTANCE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GCP_MEDIA_BUCKET_NAME=${GCP_MEDIA_BUCKET_NAME}
      - CONNECTION_TYPE=${CONNECTION_TYPE}
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/service_account.json
      - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - GOOGLE_AUTH_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
      - GOOGLE_AUTH_SECRET_KEY=${GOOGLE_AUTH_SECRET_KEY}
      - GOOGLE_AUTH_ALLOWED_DOMAINS=${GOOGLE_AUTH_ALLOWED_DOMAINS}
      # Performance tuning
      - DB_POOL_SIZE=10
      - DB_MAX_OVERFLOW=20
      - DB_POOL_TIMEOUT=30
      - DB_POOL_RECYCLE=3600
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./service_account.json:/credentials/service_account.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data: 