services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/service_account.json
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./service_account.json:/credentials/service_account.json:ro
      - ./.env:/app/.env:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data: 