services:
  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.37.2
    command: >
      /cloud_sql_proxy
      -instances=${CLOUDSQL_INSTANCE}=tcp:0.0.0.0:5432
      -credential_file=/secrets/service_account.json
    volumes:
      - ./service_account.json:/secrets/service_account.json:ro
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - cloudsql-proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data: 